### ISSUE TITLE
pull request fails

### ISSUE THREAD

**Issue by AFlyTyer** [NateDimick/funholidaysapi#1]
pi@raspberrypi-lcd:~ $ sudo docker pull ghcr.io/natedimick/funholidaysapi
Using default tag: latest
Error response from daemon: manifest unknown

Are you missing tags on your repo?

**Comment by NateDimick** [comment]
Hi, so even though I did some work a while back to make this app containerizable, no images have ever been pushed to any container registry. To get an image you'll have to build on your local machine. Hope that helps.

**Comment by AFlyTyer** [comment]
Thanks Nate
I saw references to docker and figured it was a container.  Appreciate the
response.

Cheers
R
